#! /bin/bash

DOCKER_NAME="llm-factuality"
CONTAINER_NAME=$USER"-tda4hallu"
SRC="tda4hallu" # folder to propulse in docker container
DOCKER_USER_ID=$(id -u) # to get these values type "id" in shell termilal
DOCKER_GROUP_ID=$(id -g)
CONTAINER_PORT=8899 # used in launch_container file
INNER_PORT=3344 

